# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79e87b4da8c8855f8667e88fa1667f498c00f7d66e98591c243aa781f3489b55d402d03426e7c5a40491b1b846db6c51a6daa6d00b99ccc5d760ea8c8ee4c7d

test:
  secret_key_base: 0b29f30b317d7af6a28b85abbcf6e998477d571eca711c6be1e9b144131fb39242fc8be75a700ea3b04744bbf93f7ca0459988a505bc3a665a5888316d2afe3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
